train_data_path: 'data/data_10_f_10_n_100000_samples_256_N_10_numsta_200_fading.mat'
test_data_path: 'data/data_10_f_10_n_10000_samples_256_N_10_numsta_200_fading.mat'

# Network selection
net: 'CNN'  # choices: CNN, RACNN
num_blocks: 7
num_filters: 64
kernel_size: 3

# Generate noisy channels for training
N: 256
Nx: 16
Ny: 16
SNR_range: [10, 15]

# Training parameters
batch_size: 1024
num_epochs: 200
lr: 0.001
validation_split: 0.1
optimizer: 'adam'
loss: 'mse'
train_mode: true
load_ckpt: 
gpu: 0

# Testing parameters
ckpt: 'C:\Users\SON\Desktop\RACNN\ckpt\run_CNN_20250116-215222\CNN_net_7_blocks_256_N_10_15_SNR.keras'
SNR_min: -10
SNR_max: 20
SNR_step: 5

# General settings
enable_logging: true
verbose: true
use_seed: true
seed: 2808
log_dir: 'logs'